import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Geist, Montserrat } from "next/font/google";
import { cn } from "@/lib/utils";

const montserratHeading = Montserrat({subsets:['latin'],variable:'--font-heading'});

const geist = Geist({subsets:['latin'],variable:'--font-sans'});


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });


const carter = localFont({
  src: "./CarterOne-Regular.ttf",
  variable: "--font-carter-one",
  weight: "400"
})

const degular = localFont({
  variable: "--font-degular",
  src: [
    {
      path: "./Degular-Medium.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./Degular-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={"h-full antialiased font-sans"}>
      <body className={`min-h-full flex flex-col bright ${degular.className} ${carter.variable}`}>{children}</body>
    </html>
  );
}
