/**
 * This file is auto-generated by scripts/sync-api.ts
 * Do not edit manually. Run `npm run sync-api` to regenerate.
 *
 * Generated from: https://cafemenuapi.azurewebsites.net/swagger/v1/swagger.json
 * Generated at: 2026-04-10T11:10:02.493Z
 */
export interface paths {
    "/api/Admin/Users/Search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin kullanıcıları filtreli listeler */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllUsersRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllUsersRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllUsersRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllUsersResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllUsersResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllUsersResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Admin/Users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin kullanıcı detayı getirir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminGetUserByIdResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetUserByIdResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetUserByIdResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Admin kullanıcıyı pasife çeker */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    userId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteUserResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteUserResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteUserResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Admin/Menus/Search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin menüleri filtreli listeler */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllMenusRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllMenusRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllMenusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllMenusResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllMenusResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllMenusResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Admin/Menus/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin menü detayı getirir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    menuId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminGetMenuByIdResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetMenuByIdResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetMenuByIdResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Admin menüyü pasife çeker */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    menuId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteMenuResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Admin/Menus/PublishStatus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Admin menüyü yayına alır veya yayından kaldırır */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Admin/GlobalCategories/Create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin global kategori oluşturur */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminCreateGlobalCategoryRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminCreateGlobalCategoryRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.AdminCreateGlobalCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminCreateGlobalCategoryResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminCreateGlobalCategoryResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminCreateGlobalCategoryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Admin/GlobalCategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin global kategorileri listeler */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllGlobalCategoriesResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllGlobalCategoriesResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminGetAllGlobalCategoriesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Admin/GlobalCategories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Admin global kategoriyi pasife çeker */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteGlobalCategoryResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteGlobalCategoryResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AdminDeleteGlobalCategoryResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/Register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.RegisterUserRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.RegisterUserRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.RegisterUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.RegisterUserResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.RegisterUserResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.RegisterUserResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/Login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.LoginRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.LoginRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.LoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.LoginResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.LoginResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.LoginResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/Logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.LogoutResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.LogoutResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.LogoutResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/VerifyEmail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** E-posta doğrula */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.VerifyEmailRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.VerifyEmailRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.VerifyEmailRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.VerifyEmailResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.VerifyEmailResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.VerifyEmailResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/ResendVerificationCode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Doğrulama kodunu tekrar gönder */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.ResendVerificationCodeRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.ResendVerificationCodeRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.ResendVerificationCodeRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.ResendVerificationCodeResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.ResendVerificationCodeResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.ResendVerificationCodeResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/GetMyProfile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kendi profilini getirir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetUserByIdResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetUserByIdResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetUserByIdResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/UpdateMyProfile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Kendi profilini günceller */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateUserRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateUserRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.UpdateUserRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.UpdateUserResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateUserResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateUserResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/ChangeMyPassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kendi şifremi değiştir */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.ChangeMyPasswordRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.ChangeMyPasswordRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.ChangeMyPasswordRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.ChangeMyPasswordResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.ChangeMyPasswordResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.ChangeMyPasswordResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Auth/DeleteMyAccount": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Hesabımı sil */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.DeleteMyAccountResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteMyAccountResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteMyAccountResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Category/Create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kendi menüme kategori ekle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.CreateCategoryRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.CreateCategoryRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.CreateCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.CreateCategoryResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.CreateCategoryResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.CreateCategoryResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Category/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Kendi kategorimi güncelle */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateCategoryRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateCategoryRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.UpdateCategoryRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.UpdateCategoryResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateCategoryResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateCategoryResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Category/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kendi kategori detayımı ve ürünlerini getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetCategoryByIdResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetCategoryByIdResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetCategoryByIdResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Kullanıcı kendi kategorisini pasife alır */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.DeleteCategoryResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteCategoryResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteCategoryResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Category/MyCategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kendi kategorilerimi getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetCategoriesByMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetCategoriesByMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetCategoriesByMenuResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Category/AddGlobalCategory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Global kategoriyi kendi menüme ekle */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Category/GlobalCategories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Aktif global kategorileri getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetGlobalCategoriesResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetGlobalCategoriesResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetGlobalCategoriesResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Menu/Create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Yeni bir menü oluştur */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.CreateMenuRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.CreateMenuRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.CreateMenuRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.CreateMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.CreateMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.CreateMenuResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Menu/GetMyMenu": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Kullanıcının menüsünü getirir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetMyMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetMyMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetMyMenuResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Menu/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Mevcut menüyü günceller */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateMenuRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateMenuRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.UpdateMenuRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.UpdateMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateMenuResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Menu/{menuId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Menüyü pasif duruma alır */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    menuId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.DeleteMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteMenuResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Product/Create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ürün oluştur */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.CreateProductRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.CreateProductRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.CreateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.CreateProductResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.CreateProductResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.CreateProductResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Product/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Ürün güncelle */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateProductRequest"];
                    "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateProductRequest"];
                    "application/*+json": components["schemas"]["CafeMenu.Entity.DTO.UpdateProductRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.UpdateProductResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateProductResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.UpdateProductResponse"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Product/{productId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** kullanıcıya ait ürün detayını getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetProductByIdResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetProductByIdResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetProductByIdResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Ürün sil (pasife al) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    productId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.DeleteProductResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteProductResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.DeleteProductResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Product/MyProducts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Giriş yapan kullanıcıya ait tüm ürünleri getir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetMyProductsResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetMyProductsResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetMyProductsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/PublicMenu/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public menüyü slug ile getirir */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.GetPublicMenuResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.GetPublicMenuResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.GetPublicMenuResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/PublicMenu/{slug}/Search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public menüde ürün araması yapar */
        get: {
            parameters: {
                query?: {
                    text?: string;
                };
                header?: never;
                path: {
                    slug: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CafeMenu.Entity.DTO.SearchPublicMenuProductsResponse"];
                        "application/json": components["schemas"]["CafeMenu.Entity.DTO.SearchPublicMenuProductsResponse"];
                        "text/json": components["schemas"]["CafeMenu.Entity.DTO.SearchPublicMenuProductsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuRequest": {
            /** Format: int64 */
            globalCategoryId: number;
            /** Format: int32 */
            order: number;
        };
        "CafeMenu.Entity.DTO.AddGlobalCategoryToMyMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            categoryId: number;
        };
        "CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusRequest": {
            /** Format: int64 */
            menuId: number;
            isPublished: boolean;
        };
        "CafeMenu.Entity.DTO.AdminChangeMenuPublishStatusResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            menuId: number;
            isPublished: boolean;
        };
        "CafeMenu.Entity.DTO.AdminCreateGlobalCategoryRequest": {
            name: string | null;
            /** Format: int32 */
            order: number;
        };
        "CafeMenu.Entity.DTO.AdminCreateGlobalCategoryResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            categoryId: number;
        };
        "CafeMenu.Entity.DTO.AdminDeleteGlobalCategoryResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            categoryId: number;
        };
        "CafeMenu.Entity.DTO.AdminDeleteMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            menuId: number;
        };
        "CafeMenu.Entity.DTO.AdminDeleteUserResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            deletedUserId: number;
        };
        "CafeMenu.Entity.DTO.AdminGetAllGlobalCategoriesResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            categories: components["schemas"]["CafeMenu.Entity.DTO.CategoryModel"][] | null;
        };
        "CafeMenu.Entity.DTO.AdminGetAllMenusRequest": {
            status: boolean | null;
            isPublished: boolean | null;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        "CafeMenu.Entity.DTO.AdminGetAllMenusResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            menus: components["schemas"]["CafeMenu.Entity.DTO.AdminMenuListModel"][] | null;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
        };
        "CafeMenu.Entity.DTO.AdminGetAllUsersRequest": {
            status: boolean | null;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
        };
        "CafeMenu.Entity.DTO.AdminGetAllUsersResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            users: components["schemas"]["CafeMenu.Entity.DTO.AdminUserListModel"][] | null;
            /** Format: int32 */
            page: number;
            /** Format: int32 */
            pageSize: number;
            /** Format: int32 */
            totalCount: number;
            /** Format: int32 */
            totalPages: number;
        };
        "CafeMenu.Entity.DTO.AdminGetMenuByIdResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            menu: components["schemas"]["CafeMenu.Entity.DTO.AdminMenuDetailModel"];
        };
        "CafeMenu.Entity.DTO.AdminGetUserByIdResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            user: components["schemas"]["CafeMenu.Entity.DTO.AdminUserDetailModel"];
        };
        "CafeMenu.Entity.DTO.AdminMenuDetailModel": {
            /** Format: int64 */
            menuId: number;
            /** Format: int64 */
            userId: number;
            title: string | null;
            slug: string | null;
            description: string | null;
            logoUrl: string | null;
            backgroundImageUrl: string | null;
            primaryColor: string | null;
            secondaryColor: string | null;
            accentColor: string | null;
            phoneNumber: string | null;
            address: string | null;
            instagramUrl: string | null;
            facebookUrl: string | null;
            xUrl: string | null;
            whatsappPhone: string | null;
            status: boolean;
            isPublished: boolean;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            modifiedDate: string | null;
            /** Format: date-time */
            deletedDate: string | null;
        };
        "CafeMenu.Entity.DTO.AdminMenuListModel": {
            /** Format: int64 */
            menuId: number;
            /** Format: int64 */
            userId: number;
            title: string | null;
            slug: string | null;
            status: boolean;
            isPublished: boolean;
            phoneNumber: string | null;
            address: string | null;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            modifiedDate: string | null;
            /** Format: date-time */
            deletedDate: string | null;
        };
        "CafeMenu.Entity.DTO.AdminUserDetailModel": {
            /** Format: int64 */
            userId: number;
            firstName: string | null;
            lastName: string | null;
            cafeName: string | null;
            email: string | null;
            /** Format: int64 */
            roleId: number;
            status: boolean;
            isApproved: boolean;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            modifiedDate: string | null;
            /** Format: date-time */
            deletedDate: string | null;
        };
        "CafeMenu.Entity.DTO.AdminUserListModel": {
            /** Format: int64 */
            userId: number;
            firstName: string | null;
            lastName: string | null;
            cafeName: string | null;
            email: string | null;
            /** Format: int64 */
            roleId: number;
            status: boolean;
            isApproved: boolean;
            /** Format: date-time */
            createdDate: string;
            /** Format: date-time */
            modifiedDate: string | null;
            /** Format: date-time */
            deletedDate: string | null;
        };
        "CafeMenu.Entity.DTO.CategoryDetailModel": {
            /** Format: int64 */
            categoryId: number;
            /** Format: int64 */
            menuId: number | null;
            name: string | null;
            /** Format: int32 */
            order: number;
            isGlobal: boolean;
            /** Format: int64 */
            globalCategoryId: number | null;
            products: components["schemas"]["CafeMenu.Entity.DTO.ProductModel"][] | null;
        };
        "CafeMenu.Entity.DTO.CategoryModel": {
            /** Format: int64 */
            categoryId: number;
            /** Format: int64 */
            menuId: number | null;
            name: string | null;
            /** Format: int32 */
            order: number;
            isGlobal: boolean;
            /** Format: int64 */
            globalCategoryId: number | null;
        };
        "CafeMenu.Entity.DTO.ChangeMyPasswordRequest": {
            currentPassword: string | null;
            newPassword: string | null;
            confirmNewPassword: string | null;
        };
        "CafeMenu.Entity.DTO.ChangeMyPasswordResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
        };
        "CafeMenu.Entity.DTO.CreateCategoryRequest": {
            name: string | null;
            /** Format: int32 */
            order: number;
        };
        "CafeMenu.Entity.DTO.CreateCategoryResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            categoryId: number;
        };
        "CafeMenu.Entity.DTO.CreateMenuRequest": {
            title: string | null;
            description: string | null;
            logoUrl: string | null;
            backgroundImageUrl: string | null;
            primaryColor: string | null;
            secondaryColor: string | null;
            accentColor: string | null;
            phoneNumber: string | null;
            address: string | null;
            instagramUrl: string | null;
            facebookUrl: string | null;
            xUrl: string | null;
            whatsappPhone: string | null;
            isPublished: boolean;
        };
        "CafeMenu.Entity.DTO.CreateMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            menuId: number;
            slug: string | null;
        };
        "CafeMenu.Entity.DTO.CreateProductRequest": {
            /** Format: int64 */
            categoryId: number;
            name: string | null;
            description: string | null;
            /** Format: double */
            price: number;
            imageUrl: string | null;
            isAvailable: boolean;
            isPopular: boolean;
            ingredients: string | null;
            allergens: string | null;
        };
        "CafeMenu.Entity.DTO.CreateProductResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            productId: number;
        };
        "CafeMenu.Entity.DTO.DeleteCategoryResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            categoryId: number;
        };
        "CafeMenu.Entity.DTO.DeleteMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            menuId: number;
        };
        "CafeMenu.Entity.DTO.DeleteMyAccountResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            userId: number;
        };
        "CafeMenu.Entity.DTO.DeleteProductResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            productId: number;
        };
        "CafeMenu.Entity.DTO.GetCategoriesByMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            categories: components["schemas"]["CafeMenu.Entity.DTO.CategoryModel"][] | null;
        };
        "CafeMenu.Entity.DTO.GetCategoryByIdResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            category: components["schemas"]["CafeMenu.Entity.DTO.CategoryDetailModel"];
        };
        "CafeMenu.Entity.DTO.GetGlobalCategoriesResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            categories: components["schemas"]["CafeMenu.Entity.DTO.CategoryModel"][] | null;
        };
        "CafeMenu.Entity.DTO.GetMyMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            menu: components["schemas"]["CafeMenu.Entity.DTO.MenuDetailModel"];
        };
        "CafeMenu.Entity.DTO.GetMyProductsResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            products: components["schemas"]["CafeMenu.Entity.DTO.ProductModel"][] | null;
        };
        "CafeMenu.Entity.DTO.GetProductByIdResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            product: components["schemas"]["CafeMenu.Entity.DTO.ProductModel"];
        };
        "CafeMenu.Entity.DTO.GetPublicMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            menu: components["schemas"]["CafeMenu.Entity.DTO.PublicMenuDetailModel"];
        };
        "CafeMenu.Entity.DTO.GetUserByIdResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            user: components["schemas"]["CafeMenu.Entity.DTO.UserListModel"];
        };
        "CafeMenu.Entity.DTO.LoginRequest": {
            email: string | null;
            password: string | null;
        };
        "CafeMenu.Entity.DTO.LoginResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            userId: number;
            email: string | null;
            /** Format: int64 */
            roleId: number;
            sessionToken: string | null;
            token: string | null;
        };
        "CafeMenu.Entity.DTO.LogoutResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
        };
        "CafeMenu.Entity.DTO.MenuDetailModel": {
            /** Format: int64 */
            menuId: number;
            /** Format: int64 */
            userId: number;
            title: string | null;
            slug: string | null;
            description: string | null;
            logoUrl: string | null;
            backgroundImageUrl: string | null;
            primaryColor: string | null;
            secondaryColor: string | null;
            accentColor: string | null;
            phoneNumber: string | null;
            address: string | null;
            instagramUrl: string | null;
            facebookUrl: string | null;
            xUrl: string | null;
            whatsappPhone: string | null;
            isPublished: boolean;
        };
        "CafeMenu.Entity.DTO.ProductModel": {
            /** Format: int64 */
            productId: number;
            /** Format: int64 */
            categoryId: number;
            categoryName: string | null;
            name: string | null;
            description: string | null;
            /** Format: double */
            price: number;
            imageUrl: string | null;
            isAvailable: boolean;
            isPopular: boolean;
            ingredients: string | null;
            allergens: string | null;
        };
        "CafeMenu.Entity.DTO.PublicCategoryModel": {
            /** Format: int64 */
            categoryId: number;
            name: string | null;
            /** Format: int32 */
            order: number;
            products: components["schemas"]["CafeMenu.Entity.DTO.PublicProductModel"][] | null;
        };
        "CafeMenu.Entity.DTO.PublicMenuDetailModel": {
            /** Format: int64 */
            menuId: number;
            title: string | null;
            slug: string | null;
            description: string | null;
            logoUrl: string | null;
            backgroundImageUrl: string | null;
            primaryColor: string | null;
            secondaryColor: string | null;
            accentColor: string | null;
            phoneNumber: string | null;
            address: string | null;
            instagramUrl: string | null;
            facebookUrl: string | null;
            xUrl: string | null;
            whatsappPhone: string | null;
            categories: components["schemas"]["CafeMenu.Entity.DTO.PublicCategoryModel"][] | null;
        };
        "CafeMenu.Entity.DTO.PublicMenuSearchProductModel": {
            /** Format: int64 */
            productId: number;
            /** Format: int64 */
            categoryId: number;
            categoryName: string | null;
            name: string | null;
            description: string | null;
            /** Format: double */
            price: number;
            imageUrl: string | null;
            isPopular: boolean;
            ingredients: string | null;
            allergens: string | null;
        };
        "CafeMenu.Entity.DTO.PublicProductModel": {
            /** Format: int64 */
            productId: number;
            name: string | null;
            description: string | null;
            /** Format: double */
            price: number;
            imageUrl: string | null;
            isPopular: boolean;
            ingredients: string | null;
            allergens: string | null;
        };
        "CafeMenu.Entity.DTO.RegisterUserRequest": {
            firstName: string | null;
            lastName: string | null;
            cafeName: string | null;
            email: string | null;
            password: string | null;
        };
        "CafeMenu.Entity.DTO.RegisterUserResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
        };
        "CafeMenu.Entity.DTO.ResendVerificationCodeRequest": {
            email: string | null;
        };
        "CafeMenu.Entity.DTO.ResendVerificationCodeResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int32 */
            remainingSeconds: number | null;
        };
        "CafeMenu.Entity.DTO.SearchPublicMenuProductsResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            products: components["schemas"]["CafeMenu.Entity.DTO.PublicMenuSearchProductModel"][] | null;
        };
        "CafeMenu.Entity.DTO.UpdateCategoryRequest": {
            /** Format: int64 */
            categoryId: number;
            name: string | null;
            /** Format: int32 */
            order: number;
        };
        "CafeMenu.Entity.DTO.UpdateCategoryResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            categoryId: number;
        };
        "CafeMenu.Entity.DTO.UpdateMenuRequest": {
            title: string | null;
            description: string | null;
            logoUrl: string | null;
            backgroundImageUrl: string | null;
            primaryColor: string | null;
            secondaryColor: string | null;
            accentColor: string | null;
            phoneNumber: string | null;
            address: string | null;
            instagramUrl: string | null;
            facebookUrl: string | null;
            xUrl: string | null;
            whatsappPhone: string | null;
            isPublished: boolean;
        };
        "CafeMenu.Entity.DTO.UpdateMenuResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            menuId: number;
            slug: string | null;
        };
        "CafeMenu.Entity.DTO.UpdateProductRequest": {
            /** Format: int64 */
            productId: number;
            /** Format: int64 */
            categoryId: number;
            name: string | null;
            description: string | null;
            /** Format: double */
            price: number;
            imageUrl: string | null;
            isAvailable: boolean;
            isPopular: boolean;
            ingredients: string | null;
            allergens: string | null;
        };
        "CafeMenu.Entity.DTO.UpdateProductResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            productId: number;
        };
        "CafeMenu.Entity.DTO.UpdateUserRequest": {
            firstName: string | null;
            lastName: string | null;
            cafeName: string | null;
            email: string | null;
        };
        "CafeMenu.Entity.DTO.UpdateUserResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
            /** Format: int64 */
            userId: number;
        };
        "CafeMenu.Entity.DTO.UserListModel": {
            /** Format: int64 */
            userId: number;
            firstName: string | null;
            lastName: string | null;
            cafeName: string | null;
            email: string | null;
            /** Format: int64 */
            roleId: number;
            isApproved: boolean;
            /** Format: int64 */
            currentSessionId: number | null;
        };
        "CafeMenu.Entity.DTO.VerifyEmailRequest": {
            email: string | null;
            code: string | null;
        };
        "CafeMenu.Entity.DTO.VerifyEmailResponse": {
            code: string | null;
            message: string | null;
            errors: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
